name: fuzz
descriptiob: A new Flutter project
vesion: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_database: ^9.1.7
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
